/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bhavaya_util_NativeProcess */

#ifndef _Included_org_bhavaya_util_NativeProcess
#define _Included_org_bhavaya_util_NativeProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bhavaya_util_NativeProcess
 * Method:    terminateProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_bhavaya_util_NativeProcess_terminateProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bhavaya_util_NativeProcess
 * Method:    waitForProcess
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_bhavaya_util_NativeProcess_waitForProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bhavaya_util_NativeProcess
 * Method:    getProcessEnumeration
 * Signature: (Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_org_bhavaya_util_NativeProcess_getProcessEnumeration
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
