package org.bhavaya.beans.generator;

/**
 * Generated by org.bhavaya.beans.generator.SourceCodeGenerator$DefaultGenerator on Thu Feb 19 23:38:22 GMT 2004
 *
 * @author Bhavaya
 * @version $Revision: 1.5 $
 */
public class Property2 extends org.bhavaya.beans.generator.SUPER_CLASS {

    public Property2() {
        super();
    }

    private org.bhavaya.beans.generator.PROPERTY_TYPE PROPERTY_NAME;

    public org.bhavaya.beans.generator.PROPERTY_TYPE getPROPERTY_NAME() {
        if (org.bhavaya.beans.BeanFactory.isLazy(PROPERTY_NAME)) {
            setPROPERTY_NAME((org.bhavaya.beans.generator.PROPERTY_TYPE) ((org.bhavaya.util.LoadClosure) PROPERTY_NAME).load());
        }
        if (org.bhavaya.beans.BeanFactory.isLazyNull(PROPERTY_NAME)) {
            return null;
        }
        return PROPERTY_NAME;
    }

    public void setPROPERTY_NAME(org.bhavaya.beans.generator.PROPERTY_TYPE PROPERTY_NAME) {
        boolean newValueLazy = org.bhavaya.beans.BeanFactory.isLazy(PROPERTY_NAME);
        org.bhavaya.beans.generator.PROPERTY_TYPE oldValue = this.PROPERTY_NAME;
        boolean oldValueLazy = org.bhavaya.beans.BeanFactory.isLazy(oldValue);
        if (oldValue != null && !oldValueLazy && newValueLazy) {
            PROPERTY_NAME = (org.bhavaya.beans.generator.PROPERTY_TYPE) ((org.bhavaya.util.LoadClosure) PROPERTY_NAME).load();
            newValueLazy = false;
        }
        org.bhavaya.beans.generator.PROPERTY_TYPE tempOldValue = org.bhavaya.beans.BeanFactory.isLazyNull(oldValue) ? null : oldValue;
        org.bhavaya.beans.generator.PROPERTY_TYPE tempNewValue = org.bhavaya.beans.BeanFactory.isLazyNull(PROPERTY_NAME) ? null : PROPERTY_NAME;
        this.PROPERTY_NAME = PROPERTY_NAME;
        if (!oldValueLazy && !newValueLazy) firePropertyChange("PROPERTY_NAME", tempOldValue, tempNewValue);
    }

}
