package org.bhavaya.beans.generator;

/**
 * Generated by org.bhavaya.beans.generator.SourceCodeGenerator$DefaultGenerator on Thu Feb 19 23:38:22 GMT 2004
 *
 * @author Bhavaya
 * @version $Revision: 1.5 $
 */
public class Property0 extends org.bhavaya.beans.generator.SUPER_CLASS {

    public Property0() {
        super();
    }

    private long PROPERTY_NAME;

    public long getPROPERTY_NAME() {
        return PROPERTY_NAME;
    }

    public void setPROPERTY_NAME(long PROPERTY_NAME) {
        long oldValue = this.PROPERTY_NAME;
        this.PROPERTY_NAME = PROPERTY_NAME;
        firePropertyChange("PROPERTY_NAME", oldValue, PROPERTY_NAME);
    }

}
