package org.bhavaya.beans.generator;

/**
 * Generated by org.bhavaya.beans.generator.SourceCodeGenerator$DefaultGenerator on Thu Feb 19 23:38:22 GMT 2004
 *
 * @author Bhavaya
 * @version $Revision: 1.5 $
 */
public class Property7 extends org.bhavaya.beans.generator.SUPER_CLASS {

    public Property7() {
        super();
    }

    private org.bhavaya.collection.BeanCollection PROPERTY_NAMECollection;

    public org.bhavaya.collection.BeanCollection getPROPERTY_NAMECollection() {
        if (PROPERTY_NAMECollection == null) {
            Object key = org.bhavaya.beans.BeanFactory.getKeyForBean(this);
            org.bhavaya.beans.BeanFactory collectionFactory = org.bhavaya.beans.BeanFactory.getInstance(org.bhavaya.util.ClassUtilities.getClass("org.bhavaya.beans.generator.PROPERTY_TYPE"), org.bhavaya.beans.BeanFactory.getDatasource(this));
            setPROPERTY_NAMECollection((org.bhavaya.collection.BeanCollection) collectionFactory.get(key, "INDEX_NAME"));
        } else if (org.bhavaya.beans.BeanFactory.isLazy(PROPERTY_NAMECollection)) {
            setPROPERTY_NAMECollection((org.bhavaya.collection.BeanCollection) ((org.bhavaya.util.LoadClosure) PROPERTY_NAMECollection).load());
        }
        if (PROPERTY_NAMECollection == org.bhavaya.beans.LazyBeanCollection.NULL_COLLECTION) {
            return null;
        }
        return PROPERTY_NAMECollection;
    }

    public org.bhavaya.beans.generator.PROPERTY_TYPE[] getPROPERTY_NAME() {
        if (getPROPERTY_NAMECollection() == null) return null;
        return (org.bhavaya.beans.generator.PROPERTY_TYPE[]) getPROPERTY_NAMECollection().toArray(new org.bhavaya.beans.generator.PROPERTY_TYPE[getPROPERTY_NAMECollection().size()]);
    }

    public void setPROPERTY_NAMECollection(org.bhavaya.collection.BeanCollection PROPERTY_NAMECollection) {
        boolean newValueLazy = org.bhavaya.beans.BeanFactory.isLazy(PROPERTY_NAMECollection);
        org.bhavaya.collection.BeanCollection oldValue = this.PROPERTY_NAMECollection;
        boolean oldValueLazy = org.bhavaya.beans.BeanFactory.isLazy(oldValue);
        if (oldValue != null && !oldValueLazy && newValueLazy) {
            PROPERTY_NAMECollection = (org.bhavaya.collection.BeanCollection) ((org.bhavaya.util.LoadClosure) PROPERTY_NAMECollection).load();
            newValueLazy = false;
        }
        org.bhavaya.collection.BeanCollection tempOldValue = org.bhavaya.beans.BeanFactory.isLazyNull(oldValue) ? null : oldValue;
        org.bhavaya.collection.BeanCollection tempNewValue = org.bhavaya.beans.BeanFactory.isLazyNull(PROPERTY_NAMECollection) ? null : PROPERTY_NAMECollection;
        if (oldValueLazy) this.PROPERTY_NAMECollection = org.bhavaya.beans.LazyBeanCollection.NULL_COLLECTION;
        if (!newValueLazy) super.setPROPERTY_NAMECollection(tempNewValue);
        this.PROPERTY_NAMECollection = PROPERTY_NAMECollection;
        if (!oldValueLazy && !newValueLazy) firePropertyChange("PROPERTY_NAMECollection", tempOldValue, tempNewValue);
    }

}
