/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bhavaya_ui_NativeWindow */

#ifndef _Included_org_bhavaya_ui_NativeWindow
#define _Included_org_bhavaya_ui_NativeWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bhavaya_ui_NativeWindow
 * Method:    setAlwaysOnTopWin32
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_bhavaya_ui_NativeWindow_setAlwaysOnTopWin32
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_bhavaya_ui_NativeWindow
 * Method:    flashWin32
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_bhavaya_ui_NativeWindow_flashWin32
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_bhavaya_ui_NativeWindow
 * Method:    getWin32HwndByFrame
 * Signature: (Ljava/awt/Frame;I)I
 */
JNIEXPORT jint JNICALL Java_org_bhavaya_ui_NativeWindow_getWin32HwndByFrame
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_bhavaya_ui_NativeWindow
 * Method:    getWin32HwndByFrameTitle
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bhavaya_ui_NativeWindow_getWin32HwndByFrameTitle
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
