/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bhavaya_util_Environment */

#ifndef _Included_org_bhavaya_util_Environment
#define _Included_org_bhavaya_util_Environment
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: mon1 */
/* Inaccessible static: mon2 */
/*
 * Class:     org_bhavaya_util_Environment
 * Method:    getProperty
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_bhavaya_util_Environment_getProperty
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_bhavaya_util_Environment
 * Method:    setProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_bhavaya_util_Environment_setProperty
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_bhavaya_util_Environment
 * Method:    getProperties
 * Signature: (Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_org_bhavaya_util_Environment_getProperties
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_bhavaya_util_Environment
 * Method:    getDiskSpaceInfo
 * Signature: (Ljava/lang/String;Lorg/bhavaya/util/Environment$DiskSpaceInfo;)V
 */
JNIEXPORT void JNICALL Java_org_bhavaya_util_Environment_getDiskSpaceInfo
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     org_bhavaya_util_Environment
 * Method:    getProcessCPUTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_bhavaya_util_Environment_getProcessCPUTime__
  (JNIEnv *, jclass);

/*
 * Class:     org_bhavaya_util_Environment
 * Method:    getProcessCPUTime
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_bhavaya_util_Environment_getProcessCPUTime__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bhavaya_util_Environment
 * Method:    nativeRequestThreadDump
 * Signature: (Ljava/lang/StringBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_bhavaya_util_Environment_nativeRequestThreadDump
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_bhavaya_util_Environment
 * Method:    getNumberOfProcessors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bhavaya_util_Environment_getNumberOfProcessors
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
